# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# This is a partial template. It contains only the sidecar client configurations.
# It should be complemented by the common load generator configuration.

sidecar-client:
  sidecar-client:
    endpoint: {{ .Services.Sidecar.GrpcEndpoint }}
    tls:
      mode: {{ .ClientTLS.Mode }}
      cert-path: {{ .ClientTLS.CertPath }}
      key-path: {{ .ClientTLS.KeyPath }}
      ca-cert-paths:
        {{- range .ClientTLS.CACertPaths }}
        - {{ . }}
        {{- end }}
  orderer-servers:
    {{- range .Services.Orderer }}
    - endpoint: {{ .GrpcEndpoint }}
      tls:
        mode: {{ .GrpcTLS.Mode }}
        cert-path: {{ .GrpcTLS.CertPath }}
        key-path: {{ .GrpcTLS.KeyPath }}
        ca-cert-paths:
          {{- range .GrpcTLS.CACertPaths }}
          - {{ . }}
          {{- end }}
    {{- end }}
  channel-id: {{ .Policy.ChannelID }}