# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
servers:
  {{- range .Services.Orderer }}
  - endpoint: {{ .GrpcEndpoint }}
    tls:
      mode: {{ .GrpcTLS.Mode }}
      cert-path: {{ .GrpcTLS.CertPath }}
      key-path: {{ .GrpcTLS.KeyPath }}
      ca-cert-paths:
        {{- range .GrpcTLS.CACertPaths }}
        - {{ . }}
        {{- end }}
  {{- end }}
block-size: {{ .BlockSize }}
block-timeout: {{ .BlockTimeout }}
config-block-path: {{ .ConfigBlockPath }}
send-config-block: true

logging:
  logSpec: {{ .Logging.LogSpec }}
  format: {{ .Logging.Format }}
